### PR TITLE
cpu: Fix incorrect return address after flush

### LINKED ISSUE #1707: Return address is wrong during Call instruction missprediction
It is a bug in _BPredUnit::squash_ function of src/cpu/pred/bpred_unit.cc file.
During correction of RAS due to Call instruction miss-prediction, return_addr is built using corr_target of Call instruction. However, the return_addr should be built with Call instruction's PC (return_addr = Call instruction PC + instruction size).

```
// A call has not pushed a return address to the RAS.
if (hist->call) {
    // In case of a call build the return address and
    // push it to the RAS.
    auto return_addr = hist->inst->buildRetPC(
                                    corr_target, corr_target);

    DPRINTF(Branch, "[tid:%i] [squash sn:%llu] "
            "Incorrectly predicted call: [sn:%llu,PC:%#x] "
            " Push return address %s onto RAS\n", tid,
            squashed_sn, hist->seqNum, hist->pc,
            *return_addr);
    ras->push(tid, *return_addr, hist->rasHistory);
}
```
A quick fix is shown below:
```
// A call has not pushed a return address to the RAS.
if (hist->call) {
    // In case of a call build the return address and
    // push it to the RAS.
    auto return_addr = hist->inst->buildRetPC(
                                    corr_target, corr_target);
    //bug fix
    if (hist->inst->size()) {
            return_addr->set(hist->pc + hist->inst->size());
    }
    DPRINTF(Branch, "[tid:%i] [squash sn:%llu] "
            "Incorrectly predicted call: [sn:%llu,PC:%#x] "
            " Push return address %s onto RAS\n", tid,
            squashed_sn, hist->seqNum, hist->pc,
            *return_addr);
    ras->push(tid, *return_addr, hist->rasHistory);
}
```

Also I suggest to add stats to show, which miss-predictions occurred due to BTB miss and miss-prediction by Predictor. It is important metric to optimize or understand the branch miss-prediction bottleneck specially when requiresBTBHit=true which is normally the case for modern CPU frontend. 
Due to the above mentioned bug, there was high return branch instruction miss-predictions due to Predictor (RAS). For a micro-benchmark, return branch instruction miss-prediction due to Predictor was 4.1k+ whereas return branch instruction miss-prediction due to BTB miss was 4k+. If the RAS size is big enough like 32 entries, the return address miss prediction due to RAS should be minimal (close to 0) for most benchmarks or atleast for micro-benchmarks. After the above mentioned fix, it is close to 0 (24 miss-predictions to be exact instead of 4.1k+).

I added the stats of type Vector2D in bpred_unit.hh. I added the following code in _BPredUnit::squash_ function to get stats related to miss-predictions occurred due to BTB miss and  miss-predictions by Predictor.

```
if (hist->target &&
(hist->target->instAddr() != corr_target.instAddr())) {
    stats.targetWrong[tid][hist->targetProvider]++;
    target_mismatch = true;

}

// stats for identifying miss-prediction due to BTB or predictor
if (hist->btbHit){
    stats.mispredictDueToPredictor[tid][hist->type]++;
}
else{
   stats.mispredictDueToBTBMiss[tid][hist->type]++;
}

```

### PR DESCRIPTION
**Pull request by dhschall**
An incorrect return address is pushed onto the RAS during misprediction of a call instruction. Currently, the corr_target (which is the target address of the call instruction) is pushed instead of the call PC + instruction size (instruction after the call). This issue was raised in #1707
The commit also adds new statistics to separate mispredictions due to predictor mispredictions and BTB misses.

Fixes #1707

### CODE REVIEW

**Review by powerjg — DISMISSED** [review]

File: src/cpu/pred/bpred_unit.cc [hunk 1]
```diff
@@ -358,6 +358,12 @@ BPredUnit::commitBranch(ThreadID tid, PredictorHistory* &hist)
     stats.committed[tid][hist->type]++;
     if (hist->mispredict) {
         stats.mispredicted[tid][hist->type]++;
+        // stats for identifying miss-prediction due to BTB or predictor
+        if (hist->btbHit){
```
Comment (erin-le) [inline src/cpu/pred/bpred_unit.cc]:
```suggestion
        if (hist->btbHit) {
```

File: src/cpu/pred/bpred_unit.cc [hunk 2]
```diff
@@ -358,6 +358,12 @@ BPredUnit::commitBranch(ThreadID tid, PredictorHistory* &hist)
...
+            stats.mispredictDueToPredictor[tid][hist->type]++;
+        } else{
```
Comment (erin-le) [inline src/cpu/pred/bpred_unit.cc]:
```suggestion
        } else {
```

File: src/cpu/pred/bpred_unit.cc [hunk 3]
```diff
@@ -649,6 +653,12 @@ BPredUnit::BPredUnitStats::BPredUnitStats(BPredUnit *bp)
               "Number of branches finally committed "),
       ADD_STAT(mispredicted, statistics::units::Count::get(),
               "Number of committed branches that were mispredicted."),
+      ADD_STAT(mispredictDueToPredictor, statistics::units::Count::get(),
+              "Number of committed branches that were mispredicted by the "
+              "predictor."),
+        ADD_STAT(mispredictDueToBTBMiss, statistics::units::Count::get(),
+              "Number of committed branches that were mispredicted because of "
+              "a BTB miss."),
```
Comment (erin-le) [inline src/cpu/pred/bpred_unit.cc]:
```suggestion
      ADD_STAT(mispredictDueToPredictor, statistics::units::Count::get(),
              "Number of committed branches that were mispredicted by the "
              "predictor."),
      ADD_STAT(mispredictDueToBTBMiss, statistics::units::Count::get(),
              "Number of committed branches that were mispredicted because of "
              "a BTB miss."),
```

**Review by erin-le — CHANGES_REQUESTED** [review]
Thank you for your contribution! I noticed some minor inconsistencies with the whitespace; could you fix them before this gets merged?

**Comment by dhschall** [comment]
Thank you, @erin-le, for pointing out the white space issues.
I made a small update as I realized that a BTB hit is only required if the branch was taken.

**Comment by dhschall** [comment]
Btw. @powerjg and @erin-le, feel free to tag or assign me if there are other issues related to the branch predictor or changes I made.

**Review by powerjg — APPROVED** [review]

**Review by erin-le — APPROVED** [review]
