### PR TITLE
misc: fix clang13 overloaded-virtual warning

### LINKED ISSUE #437: `'bind' hides overloaded virtual functions` compilation errors with clang
**Describe the bug**

Compiling on gem5 returns a `...:bind' hides overloaded virtual functions` compilation when compiling with any of our supported clang compilers.

This appears to be caused by code in systemc: [src/systemc/ext/tlm_utils/../tlm_core/2/sockets/initiator_socket.hh](https://github.com/gem5/gem5/blob/70b6b53e54fae8a60004f94c4d6ae54bf8b5651d/src/systemc/ext/tlm_core/2/sockets/initiator_socket.hh).

I believe this was introduced, somehow, via this PR: https://github.com/gem5/gem5/pull/363 (which was fixing the same/a similar bug in GCC).

**Affects version**

Affects the develop branch at the time of writing. Verified to be faulty at Revision 70b6b53e54fae8a60004f94c4d6ae54bf8b5651d

**To Reproduce**

```sh
cd gem5

docker run -u$UID:$GID -v$(pwd):/work -w /work -it --rm ghcr.io/gem5/clang-version-14:latest scons build/All/gem5.opt -j$(nproc)
```

This creates a docker container with clang-14 which `scons` (within the Docker container) will use to compiler gem5.

**Terminal Output**

[Here](https://github.com/gem5/gem5/files/12873750/26_all-compilers.clang-version-7.fast.txt) a a log of the failure.

This error repeats itself, the output log is attached. The key information is:

```sh
src/systemc/ext/tlm_utils/../tlm_core/2/sockets/initiator_socket.hh:100:5: error: 'tlm::tlm_base_initiator_socket<32, tlm::tlm_fw_transport_if<tlm::tlm_base_protocol_types>, tlm::tlm_bw_transport_if<tlm::tlm_base_protocol_types>, 1, sc_core::SC_ONE_OR_MORE_BOUND>::bind' hides overloaded virtual functions [-Werror,-Woverloaded-virtual]
    bind(base_target_socket_type &s)
    ^
src/systemc/ext/tlm_utils/../tlm_core/2/sockets/initiator_socket.hh:180:37: note: in instantiation of template class 'tlm::tlm_base_initiator_socket<32, tlm::tlm_fw_transport_if<tlm::tlm_base_protocol_types>, tlm::tlm_bw_transport_if<tlm::tlm_base_protocol_types>, 1, sc_core::SC_ONE_OR_MORE_BOUND>' requested here
class tlm_initiator_socket : public tlm_base_initiator_socket<
                                    ^
src/systemc/ext/tlm_utils/simple_initiator_socket.h:38:12: note: in instantiation of template class 'tlm::tlm_initiator_socket<32, tlm::tlm_base_protocol_types, 1, sc_core::SC_ONE_OR_MORE_BOUND>' requested here
    public tlm::tlm_initiator_socket<BUSWIDTH, TYPES, 1, POL>,
           ^
src/systemc/ext/tlm_utils/simple_initiator_socket.h:157:12: note: in instantiation of template class 'tlm_utils::simple_initiator_socket_b<sc_gem5::Gem5ToTlmBridge<32>, 32, tlm::tlm_base_protocol_types, sc_core::SC_ONE_OR_MORE_BOUND>' requested here
    public simple_initiator_socket_b<MODULE, BUSWIDTH, TYPES>
           ^
src/systemc/tlm_bridge/gem5_to_tlm.hh:154:46: note: in instantiation of template class 'tlm_utils::simple_initiator_socket<sc_gem5::Gem5ToTlmBridge<32>, 32, tlm::tlm_base_protocol_types>' requested here
        Gem5ToTlmBridge<BITWIDTH>, BITWIDTH> socket;
                                             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/type_traits:1295:66: note: in instantiation of template class 'sc_gem5::Gem5ToTlmBridge<32>' requested here
    : public integral_constant<bool, __is_base_of(_Base, _Derived)>
                                                                 ^
ext/pybind11/include/pybind11/detail/common.h:880:26: note: (skipping 1 context in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    = bool_constant<std::is_base_of<Base, Derived>::value && !std::is_same<Base, Derived>::value>;
                         ^
ext/pybind11/include/pybind11/pybind11.h:1495:5: note: in instantiation of template type alias 'is_strict_base_of' requested here
    using is_base = detail::is_strict_base_of<T, type_>;
    ^
ext/pybind11/include/pybind11/pybind11.h:1498:80: note: in instantiation of template type alias 'is_base' requested here
    struct is_valid_class_option : detail::any_of<is_holder<T>, is_subtype<T>, is_base<T>> {};
                                                                               ^
ext/pybind11/include/pybind11/detail/common.h:719:31: note: in instantiation of template class 'pybind11::class_<sc_gem5::Gem5ToTlmBridge<32>, sc_gem5::Gem5ToTlmBridgeBase, std::unique_ptr<sc_gem5::Gem5ToTlmBridge<32>, pybind11::nodelete> >::is_valid_class_option<std::unique_ptr<sc_gem5::Gem5ToTlmBridge<32>, pybind11::nodelete> >' requested here
using all_of = bool_constant<(Ts::value && ...)>;
```

### PR DESCRIPTION
**Pull request by powerjg**
Like #363 clang is also unhappy about the overloaded virtual. However,
clang needs to have the diagnostic in a different place

Fixes #437

Change-Id: I3cd30051552acd5c8689928ebca137c71505c340
Signed-off-by: Jason Lowe-Power <jason@lowepower.com>

### CODE REVIEW

**Comment by powerjg** [comment]
@wmin0 can you take a look? This seems similar to your commit #363

**Comment by wmin0** [comment]
Can we just have both instead of removing the declaration in sc_port.hh? I will try it next Monday.

**Review by BobbyRBruce — APPROVED** [review]

File: src/systemc/ext/tlm_core/2/sockets/initiator_socket.hh [hunk 1]
```diff
@@ -51,6 +51,10 @@ template <unsigned int BUSWIDTH, typename FW_IF, typename BW_IF, int N,
           sc_core::sc_port_policy POL>
 class tlm_base_target_socket;
 
+// The overloaded virtual is intended in SystemC, so we'll disable the warning.
```
Comment (wmin0) [inline src/systemc/ext/tlm_core/2/sockets/initiator_socket.hh:54]: I have checked only adding this back can make two compiler happy. Would you like to change? Thanks.
