### PR TITLE
cpu-o3: stall fetch from commit when trap event is pending

### LINKED ISSUE #2344: O3 executes user level code with elevated privileges after interrupt in RISC-V
**Describe the bug**
When an interrupt comes and the core is drained to handle it, the fetch stage is not stalled after the trap event is scheduled, which, with RISC-V in particular, terminates in execution of user level code in machine mode.

**Affects version**
develop (dd43f9d1bd)

**gem5 Modifications**
with PR #2311

**Excerpt from the trace**
Here's an annotated excerpt from a trace of a full system RISC-V simulation with ruby where this happens (and causes a crash with a `prefetch_r` instruction):

```shell
# Interrupt comes
272121450000: board.processor.cores0.core.isa: setting miscreg time (10) to 0x19f3971.
272121450000: board.platform.clint: mtip posted - thread: 0, mtime: 27212145, mtimecmp: 27212145
272121450000: board.processor.cores0.core.interrupts: interrupt 7:0 posted

# After a few cycles the trap event is generated, changing the privilege mode to Machine
272121476500: board.processor.cores0.core.commit: Interrupt detected.
272121476500: board.processor.cores0.core: Interrupt interrupt being handled
272121476500: board.processor.cores0.core.isa: Reading MiscReg PRV (0): 0. # U-mode
272121476500: board.processor.cores0.core.isa: Setting MiscReg PRV (0) to 0x3 # M-mode
272121476500: board.processor.cores0.core.isa: Reading MiscReg MTVEC (79): 0x800003d0. # Interrupt handler
272121476500: board.processor.cores0.core.commit: Generating trap event for [tid:0]

# Next cycle we keep fetching user level code
272121477000: board.processor.cores0.core.fetch: Attempting to fetch from [tid:0]
272121477000: board.processor.cores0.core.fetch: [tid:0] Adding instructions to queue to decode.
272121477000: board.processor.cores0.core.decoder: Requesting bytes 0x601300b4 from address 0x2aadd93ab4
272121477000: board.processor.cores0.core.decoder: Requesting bytes 0x85330015 from address 0x2aadd93ab8
272121477000: board.processor.cores0.core.decoder: Decoding instruction 0x00156013 at address 0x2aadd93ab6
272121477000: board.processor.cores0.core.decoder: Decode: Decoded prefetch_r instruction: 0x500080d800156013
272121477000: global: DynInst: [sn:10587791] Instruction created. Instcount for board.processor.cores0.core = 1
272121477000: board.processor.cores0.core.fetch: [tid:0] Instruction PC (0x2aadd93ab6=>0x2aadd93aba).(0=>1) created [sn:10587791].

# In this case, an instruction goes through and the address translation is skipped due to M-mode
272121479000: board.processor.cores0.core.iew: [tid:0] Issue: Memory instruction encountered, adding to LSQ.
272121479000: board.processor.cores0.core.isa: Reading MiscReg PRV (0): 0x3.
272121479500: board.processor.cores0.core.iew: Execute: Calculating address for memory reference.
272121479500: board.processor.cores0.core.iew.lsq.thread0: Executing load PC (0x2aadd93ab6=>0x2aadd93aba).(0=>1), [sn:10587791]
272121479500: global: RegFile: Access to int register 13, has data 0x3f9d269900 # Virtual address
272121479500: board.processor.cores0.core.iew.lsq.thread0: Read called, load idx: 3073012, store idx: 60231, storeHead: 60230 addr: 0x3f9d269900
272121479500: board.processor.cores0.core.iew.lsq.thread0: Doing memory access for inst [sn:10587791] PC (0x2aadd93ab6=>0x2aadd93aba).(0=>1)
272121479500: board.processor.cores0.data_sequencer.response_ports0: Timing request for address 0x3f9d269900 on port 0

# Because we go through with the virtual address the sequencer assumes it's a pio address, which is what actually causes the crash later on
272121479500: board.processor.cores0.data_sequencer.response_ports0: Request address 0x3f9d269900 assumed to be a pio address # 
272121479500: board.processor.cores0.core.iew.lsq.thread0: Memory request (pkt: SoftPFReq [3f9d269900:3f9d269900]) from inst [sn:10587791] was sent (cache is blocked: 0, cache_got_blocked: 0)

# A few cycles later the trap event executes and the core jumps to the interrupt handler
272121483500: board.processor.cores0.core.commit: Squashing from trap, restarting at PC (0x800003d0=>0x800003d4).(0=>1)
272121483500: board.processor.cores0.core: Activity: 9
272121483500: board.processor.cores0.core.commit: [tid:0] ROB has 0 insts & 256 free entries.
272121483500: board.processor.cores0.core.commit: Activity This Cycle.
272121483500: board.processor.cores0.core: Activity: 8
272121483500: board.processor.cores0.core: Scheduling next tick!
272121484000: board.processor.cores0.core:
272121484000: board.processor.cores0.core.fetch: [tid:0] Squashing instructions due to squash from commit.
272121484000: board.processor.cores0.core.fetch: [tid:0] Squash from commit.
272121484000: board.processor.cores0.core.fetch: [tid:0] Squashing, setting PC to: (0x800003d0=>0x800003d4).(0=>1).

# Response comes back and cast error happens on LSQ, which ultimately crashes gem5
272121583000: board.processor.cores0.core.iew.lsq: Got error packet back for address: 0X3F9D269900
```

**Expected behavior**
Fetch should stall until the trap event is executed.

### PR DESCRIPTION
**Pull request by saul44203**
This commit stalls O3's fetch stage when a trap event is signaled to be pending from commit. Fixes #2344.

### CODE REVIEW

File: src/cpu/o3/fetch.cc [hunk 1]
```diff
@@ -1330,6 +1334,13 @@ Fetch::fetch(bool &status_change)
 void
 Fetch::recvReqRetry()
 {
+    // If a trap is pending to execute, discard the retry
+    if (retryPkt != NULL && fetchStatus[retryTid] == TrapPending) {
+        delete retryPkt;
+        retryPkt = NULL;
+        retryTid = InvalidThreadID;
+    }
```
Comment (saul44203) [inline src/cpu/o3/fetch.cc:1342]: Tested this PR with realview64 O3 ARM FS tests to check if it breaks other ISAs. This led me to catch a bug where an I-cache retry attempt would come when fetch was stalled due to a pending interrupt trap (`fetchStatus = TrapPending`), crashing on an assertion where `fetchStatus` was expected to be `IcacheWaitRetry`.

This is the relevant code, which discards the retry (which I think is safe but I'm open to discussion).

This makes the test pass. Also open to do more tests.

**Review by powerjg — COMMENTED** [review]
lgtm. @giactra or @rjc-arch do you want to take a look?

**Comment by powerjg** [comment]
@dhschall you may be able to provide a review as well.

File: src/cpu/o3/fetch.cc (hunk 1 above)
Comment (dhschall) [reply src/cpu/o3/fetch.cc:1342]: That looks like a reasonable way to fix it. Thanks for doing this test and catching this case.

**Review by dhschall — COMMENTED** [review]
Thanks for tracing this down! It looks like the correct way to fix it.
Which ISA's did you test?

**Review by dhschall — APPROVED** [review]

**Comment by saul44203** [comment]
> Thanks for tracing this down! It looks like the correct way to fix it. Which ISA's did you test?

Apart from ARM's realview64 FS test with O3 that I mentioned my team has been running a few RISC-V simulations with this patch without issues.
