### PR TITLE
arch-riscv: Enable RVV run in Minor and O3 CPU

### LINKED ISSUE #144: RISC-V RVV vset*vl* instructions can execute bad in out-of-order (O3) mode
**Describe the bug**
RVV vset\*vl\* instructions can be executed bad in out-of-order (O3) mode. If vset\*vl\* is in mis-predicted branch it changes the 'VL' value in decoder and the vector instructions afterwards are decoded/executed in correspondence with 'VL' value which was set in squashed instruction.

**Affects version**
Found in [arch-riscv: Relation chain on RVV support #83](https://github.com/gem5/gem5/pull/83)  PR.

**To Reproduce**
The reproducer is in https://github.com/vmskv/gem5/tree/vmskv/rvv_bad_o3_vsetvl_execuion/riscv_o3_bad_vsetvl_execution_reproducer 
The steps to reproduce are in [README.txt](https://github.com/vmskv/gem5/blob/vmskv/rvv_bad_o3_vsetvl_execuion/riscv_o3_bad_vsetvl_execution_reproducer/README.txt)

**Expected behavior**
If vset\*vl\* is squashed the last previous correct 'VL' value should be used to decode the vector instructions.

**Host Operating System**
Ubuntu 20.04

**Guest ISA**
RISC-V.

### PR DESCRIPTION
**Pull request by rogerchang23424**
Changes in the PR:

1. Change the vset\*vl\* instructions to jump/branch family, and implement the branchTarget.
2. Move the Vl and Vtype from decoder to PCState
3. get VL, VTYPE and VLENB value from PCState
4. Remove vtype checking in construction so that the minor and o3 cpu and decode the instructions after the vset\*vl\*

### CODE REVIEW

**Comment by rogerchang23424** [comment]
Related issue: #144
To enable run RVV in minor, #225 is required

**Review by BobbyRBruce — DISMISSED** [review]
Loving the progress we're making on RVV! Great work!

**Comment by BobbyRBruce** [comment]
I'll give this another day to give others a chance to see this. Looks good to me but I'm not a RISC-V expert.

@hnpl : Can you look this over?

**Comment by rogerchang23424** [comment]
cc: @vmskv @adriaarmejach @alvaromorenomv

**Comment by aarmejach** [comment]
The code LGTM to enable `minor` and `o3` now. But I have a questions and a concern:

Why do we need to replicate the `vtype` and  `vl` register state in decode? I think that using the `MISCREG` architectural values will simplify things. 

My concern is that with this path the issue #144 might still trigger. Say you execute and commit a `vsetvl` instruction, changing `vtype` and `vl` state, and then the `vsetvl` instructions is squashed due to a previous branch missprediction. The newly decoded instructions after recovering from the missprediction will see the modified `vtype` and `vl` state. Maybe I am wrong, but this might still be an issue.

I am all in on enabling Minor and O3 ASAP, so if #144 is easy to fix in this patch that would be great. 

Since we are discussing, I am interested in trying to implement a proposal that does not always squash after. Making `vsetvl`instructions behave like branches that update `vtype` and `vl` state at commit time make things quite easy. If at commit time `new_vtype != previous_vtype or new_vl != previous_vl` you squashAll (method already exists), otherwise do nothing. With this approach decode can use the current architectural state for `vtype` and `vl`. This will enable loops that have the same `vsetvl` instruction, common case, to execute much faster.

**Comment by rogerchang23424** [comment]
> The code LGTM to enable `minor` and `o3` now. But I have a questions and a concern:
> 
> Why do we need to replicate the `vtype` and `vl` register state in decode? I think that using the `MISCREG` architectural
> values will simplify things.

It's better to remove the `vtype` and `vl` in decoder to make it more simply. However, the `StaticInst` of vector instructions require the `vtype` and `vl` parameters to decode(construct) them.

> My concern is that with this path the issue #144 might still trigger. Say you execute and commit a `vsetvl` instruction, changing `vtype` and `vl` state, and then the `vsetvl` instructions is squashed due to a previous branch missprediction. The newly decoded instructions after recovering from the missprediction will see the modified `vtype` and `vl` state. Maybe I am wrong, but this might still be an issue.

I can't guarantee the issue #144 will be solved after the change applied, I have tested the vector with https://github.com/ksco/riscv-tests/tree/spike/isa/rv64uv, [rvv-intrinsic-doc](https://github.com/riscv-non-isa/rvv-intrinsic-doc)(all of examples are passed, except for str* since it require `vleff*` be implemented ) and [riscv_o3_bad_vsetvl_execution_reproducer](https://github.com/vmskv/gem5/tree/vmskv/rvv_bad_o3_vsetvl_execuion/riscv_o3_bad_vsetvl_execution_reproducer),all of them are passed. The example of #144 shows the correct result for both atomic and o3 cpu.

> I am all in on enabling Minor and O3 ASAP, so if #144 is easy to fix in this patch that would be great.
> 
> Since we are discussing, I am interested in trying to implement a proposal that does not always squash after. Making `vsetvl`instructions behave like branches that update `vtype` and `vl` state at commit time make things quite easy. If at commit time `new_vtype != previous_vtype or new_vl != previous_vl` you squashAll (method already exists), otherwise do nothing. With this approach decode can use the current architectural state for `vtype` and `vl`. This will enable loops that have the same `vsetvl` instruction, common case, to execute much faster.

OK, I will change the vset\*vl\* instruction to branch like instruction,  I have saw the implementation before https://github.com/hnpl/plct-gem5-1/commits/rvv-cpu.

**Comment by rogerchang23424** [comment]
Rebase only

**Comment by hnpl** [comment]
>> The code LGTM to enable minor and o3 now. But I have a questions and a concern:
>>
>> Why do we need to replicate the vtype and vl register state in decode? I think that using the MISCREG architectural
values will simplify things.

> It's better to remove the vtype and vl in decoder to make it more simply. However, the StaticInst of vector instructions require the vtype and vl parameters to decode(construct) them.

I think having the decoder maintaining its own state of vtype and vl regs is okay because it looks like the RISCV decoder does not have access to the architectural state of the core, i.e. the core's ThreadContext (tc) or ExecContext (xc). 

> OK, I will change the vset*vl* instruction to branch like instruction, I have saw the implementation before https://github.com/hnpl/plct-gem5-1/commits/rvv-cpu.

I want to note that this implementation takes a different direction than having the vtype and vl states in decoder.
Instead of having vtype and vl in decoder, the vtype and vl of an instruction are stored in the instruction's PCState, which is a part of every DynInst.

Having vtype and vl in PCState is necessary if the vconfig instructions are treated as branch instructions. This is because for branch instructions, the core will determine whether the branch instruction is correctly executed by comparing the PCStates. This is reflected in this change here, https://github.com/hnpl/plct-gem5-1/commit/b061650493901143ccf60585ef87e46687e2949a#diff-366ad84d19b6100d495edd74366ab39abe982fb2265e611baa839aa9d513b3d9R101.

This is how the vtype and vl are updated,
https://github.com/hnpl/plct-gem5-1/commit/3013eb0c5738bdc588d4d830cf33351d562176a7#diff-0c78d5a93acb1d90c9296beb8cfee1f57b97aec841507f8681158cb529168fa5R90

This is where the next vector instruction acquires the vtype and vl from the previous instruction,
https://github.com/hnpl/plct-gem5-1/commit/8d946c742ea093445e406e518a7e6b485e0f2a75#diff-93a5a8581aba54897a09350ea3f735d79ef1fd441f1970010c765647f6fb4489R130

**Comment by rogerchang23424** [comment]
Thanks @hnpl

File: src/arch/riscv/isa.cc [hunk 1]
```diff
@@ -503,9 +504,26 @@ ISA::readMiscReg(RegIndex idx)
...
+      case MISCREG_VTYPE:
+        {
+            auto rpc = tc->pcState().as<PCState>();
+            RegVal val = 0;
+            VTYPE vtype = rpc.vtype();
+            val = (RegVal)vtype;
+            if (_rvType == RV64) {
+                val &= ~(1 << 31);
+                val |= (vtype.vill << 63);
+            }
```
Comment (aarmejach) [inline src/arch/riscv/isa.cc]: This made me realize that the current VTYPE BitUnion is defined as 32bit. I think RVV requires at least RV64, so VTYPE should be at least 64 bits. This would also simplify this code, as the cast to RegVal would be enough.

File: src/arch/riscv/isa.cc [hunk 2]
```diff
@@ -503,9 +504,26 @@ ISA::readMiscReg(RegIndex idx)
...
+            return rpc.vlenb();
+        }
+      case MISCREG_VTYPE:
+        {
+            auto rpc = tc->pcState().as<PCState>();
+            RegVal val = 0;
+            VTYPE vtype = rpc.vtype();
+            val = (RegVal)vtype;
+            if (_rvType == RV64) {
+                val &= ~(1 << 31);
```
Comment (aarmejach) [inline src/arch/riscv/isa.cc]: If we keep this line I'd change the `~(1 << 31)` for the actual mask or `~(1U << 31)`. Just to avoid issues on 32-bit systems or compilers interpreting it as a 64-bit constant.

File: src/arch/riscv/pcstate.hh [hunk 3]
```diff
@@ -56,15 +57,28 @@ constexpr enums::RiscvType RV64 = enums::RV64;
 
 class PCState : public GenericISA::UPCState<4>
 {
-  private:
+  protected:
+    typedef GenericISA::UPCState<4> Base;
+
     bool _compressed = false;
     RiscvType _rvType = RV64;
```
Comment (aarmejach) [inline src/arch/riscv/pcstate.hh:64]: Should this be initialized with `isa->rvType()`?

File: src/arch/riscv/pcstate.hh [hunk 4]
```diff
@@ -56,15 +57,28 @@ constexpr enums::RiscvType RV64 = enums::RV64;
...
+    uint64_t _vlenb = 32;
+    VTYPE _vtype = 0x80000000; // vtype.vill = 1 at initial;
```
Comment (aarmejach) [inline src/arch/riscv/pcstate.hh]: If VTYPE BitUnion is changed to 64 bits this needs to be updated

**Review by aarmejach — COMMENTED** [review]
This is great! I was suggesting to go this way on a future iteration :)

Overall this LGTM, I have left a few minor coments.

File: src/arch/riscv/isa.cc (hunk 2 above)
Comment (rogerchang23424) [reply src/arch/riscv/isa.cc]: Change VTYPE to BitUnion64

File: src/arch/riscv/isa.cc (hunk 1 above)
Comment (rogerchang23424) [reply src/arch/riscv/isa.cc]: Change VTYPE to BitUnion64

File: src/arch/riscv/pcstate.hh (hunk 3 above)
Comment (rogerchang23424) [reply src/arch/riscv/pcstate.hh:64]: It has initialized in isa.newPCState https://github.com/gem5/gem5/blob/stable/src/arch/riscv/isa.hh#L90

**Comment by rogerchang23424** [comment]
```
Logging call to command: /__w/gem5/gem5/build/ALL/gem5.opt -d /tmp/gem5outppd_thks -re --silent-redirect /__w/gem5/gem5/configs/example/gem5_library/checkpoints/riscv-hello-restore-checkpoint.py
Starting Test Suite: test-gem5-library-riscv-hello-restore-checkpoint-ALL-x86_64-opt 
Starting Test Case: test-gem5-library-riscv-hello-restore-checkpoint-ALL-x86_64-opt
Test: test-gem5-library-riscv-hello-restore-checkpoint-ALL-x86_64-opt Failed
Starting Test Case: test-gem5-library-riscv-hello-restore-checkpoint-ALL-x86_64-opt-MatchRegex
Test: test-gem5-library-riscv-hello-restore-checkpoint-ALL-x86_64-opt-MatchRegex Failed
```

@BobbyRBruce, We need to run `util/cpt_upgrader.py` to update the `riscv-hello-example-checkpoint` resource

**Review by aarmejach — APPROVED** [review]
LGTM but it'd be great if we can get another +1.

**Review by powerjg — APPROVED** [review]
Wow! Way simpler than I expected!

Thanks for putting this together!

**Comment by powerjg** [comment]
@BobbyRBruce, we're just waiting on you to update the checkpoints in gem5-resources. Let me know if I can help.

**Review by BobbyRBruce — APPROVED** [review]
Sorry for the delay. The resource is updated and the tests should pass now.
