### PR TITLE
arch-riscv: Fix incorrect vector unit-stride segment load instructions

### LINKED ISSUE #1668: Incorrect riscv vector unit-stride segment load/store instructions
**Describe the bug**
The execution result of the riscv vector unit-stride segment load/store instruction is not as expected. The picture of trace here shows the bug. (vlen=128).

The results in trace do not conform to the description in the [specification](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#sec-aos).

截屏2024-10-12 下午7 30 36

The correct result of vlseg2e8.v(0x106b4) shoule be:
```
vlseg2e8_v_micro v0, (a0), zero : SimdUnitStrideSegmentedLoad :  D=[00020406_080a0c0e_10121416_181a1c1e]
vlseg2e8_v_micro v1, (a0), zero : SimdUnitStrideSegmentedLoad :  D=[01030507_090b0d0f_11131517_191b1d1f]
```

**Affects version**
Develop branch. Commit [a8f88abfb12f772f496aad2b9866476f7ebb575c](https://github.com/gem5/gem5/tree/a8f88abfb12f772f496aad2b9866476f7ebb575c).

**gem5 Modifications**
#1669

**To Reproduce**
[Here](https://github.com/user-attachments/files/17349831/vlseg.tar.gz) is a simple test. Use the `vlseg` elf file and `se.py` script in `gz` package file to simulate. And dump the Exec trace.

**Terminal Output**
If applicable, add the terminal output here. If long, only include the relevant lines.
Please put the terminal output in code blocks. I.e.:

```shell
/data00/home/hongzhibo/share/benchmark/vlseg/vlseg
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version DEVELOP-FOR-24.1
gem5 compiled Oct 12 2024 14:28:11
gem5 started Oct 12 2024 18:34:40
gem5 executing on n37-094-005, pid 385420
command line: ./build/RISCV/gem5.opt --debug-flags=Exec --debug-start=45690500 --debug-file=trace.out configs/deprecated/example/se.py --cmd /data00/home/hongzhibo/share/benchmark/vlseg/vlseg

warn: The se.py script is deprecated. It will be removed in future releases of  gem5.
Global frequency set at 1000000000000 ticks per second
src/mem/dram_interface.cc:690: warn: DRAM device capacity (8192 Mbytes) does not match the address range assigned (512 Mbytes)
src/arch/riscv/isa.cc:278: info: RVV enabled, VLEN = 128 bits, ELEN = 64 bits
src/base/statistics.hh:279: warn: One of the stats is a legacy stat. Legacy stat is a stat that does not belong to any statistics::Group. Legacy stat is deprecated.
system.remote_gdb: Listening for connections on port 7000
**** REAL SIMULATION ****
src/sim/simulate.cc:199: info: Entering event queue @ 0.  Starting simulation...
src/sim/syscall_emul.cc:97: warn: ignoring syscall set_robust_list(...)
      (further warnings will be suppressed)
src/sim/mem_state.cc:448: info: Increasing stack size by one page.
src/sim/syscall_emul.cc:86: warn: ignoring syscall mprotect(...)
Exiting @ tick 52690500 because exiting with last active thread context
```

**Expected behavior**
You can see the above picture from the trace file. The results of the vlseg2e8.v instruction do not meet the riscv vector specifications.

**Host Operating System**
Debian 12.

**Host ISA**
X86

**Compiler used**
gcc 14

### LINKED ISSUE #1856: [RISC-V] Incorrect results on latest stable branch (commit 63d25922)
**Describe the bug**
The latest Stable branch (commit 63d25922) is giving incorrect results

**Affects version**
stable branch commit 63d25922

**gem5 Modifications**
None

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

1. Compile gem5 with command ...  scons build/RISCV/gem5.opt

```
uint16_t sumOfElements(const uint8_t* src,size_t nLength) 
{
  size_t processed_size = 0;
  size_t output_size=(nLength);
  size_t output_loop_size=(output_size/32);
  uint8_t* in_ptr = (uint8_t *)src;

  vuint8m1_t  vecIn;
  vuint16m2_t vecAcc;
  
  size_t vlmax = __riscv_vsetvl_e8m1(nLength);
  vecAcc = __riscv_vmv_v_x_u16m2(0, vlmax);
  vuint16m1_t redSum =  __riscv_vmv_v_x_u16m1(0, vlmax);
  size_t vl;

  do
  {
	  vl = __riscv_vsetvl_e8m1(nLength - processed_size);
	  vecIn = __riscv_vle8_v_u8m1(in_ptr, vl);
	  vecAcc = __riscv_vwaddu_wv_u16m2(vecAcc, vecIn, vl);
	  in_ptr += vl;
	  processed_size += vl;
  }while(processed_size<nLength);
  redSum =  __riscv_vredsum_vs_u16m2_u16m1(vecAcc, redSum, vlmax);
  uint16_t sum = __riscv_vmv_x_s_u16m1_u16(redSum);
  return sum;
}
```
**Expected behavior**
Spike and gem5 branch commit b1a44b89c7bae73fae2dc547bc1f871452075b85 (HEAD -> stable, tag: v24.0.0.1, tag: v24.0, origin/stable, origin/HEAD) gives expected results

Trace from gem5 tag: v24.0.0.1
```
6295000: system.cpu: T0 : 0x10304 @_Z13sumOfElementsPKhm    : vsetvli a3, a1, e16, m2, ta, ma : SimdConfig :  D=0x0000000000000020
6353750: system.cpu: T0 : 0x10308 @_Z13sumOfElementsPKhm+4    : vle8_v v1, (a0)           
6353750: system.cpu: T0 : 0x10308 @_Z13sumOfElementsPKhm+4. 0 : vle8_v_micro v1, 0(a0), v1 : SimdUnitStrideLoad :  D=[00010203_04050607_08090a0b_0c0d0e0f_10111213_14151617_18191a1b_1c1d1e1f] A=0x1c160
6360000: system.cpu: T0 : 0x1030c @_Z13sumOfElementsPKhm+8    : vmv_v_i v6, v6, 0         
6360000: system.cpu: T0 : 0x1030c @_Z13sumOfElementsPKhm+8. 0 : vmv_v_i_micro v6, v0, 0    : SimdMisc :  D=[00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000]
6361250: system.cpu: T0 : 0x1030c @_Z13sumOfElementsPKhm+8. 1 : vmv_v_i_micro v7, v1, 0    : SimdMisc :  D=[00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000]
6362500: system.cpu: T0 : 0x10310 @_Z13sumOfElementsPKhm+12    : vsetvli zero, a3, e16, m1, ta, ma : SimdConfig :  D=0x0000000000000010
6432500: system.cpu: T0 : 0x10314 @_Z13sumOfElementsPKhm+16    : vmv_v_i v4, v4, 0         
6432500: system.cpu: T0 : 0x10314 @_Z13sumOfElementsPKhm+16. 0 : vmv_v_i_micro v4, v0, 0    : SimdMisc :  D=[00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000]
6433750: system.cpu: T0 : 0x10318 @_Z13sumOfElementsPKhm+20    : vsetvli zero, a3, e8, m1, ta, ma : SimdConfig :  D=0x0000000000000020
6445000: system.cpu: T0 : 0x1031c @_Z13sumOfElementsPKhm+24    : c_add a0, a3               : IntAlu :  D=0x000000000001c180
6448750: system.cpu: T0 : 0x1031e @_Z13sumOfElementsPKhm+26    : vwaddu_wv v2, v6, v1      
6448750: system.cpu: T0 : 0x1031e @_Z13sumOfElementsPKhm+26. 0 : vwaddu_wv_micro v2, v6, v1 : SimdAdd :  D=[00000100_02000300_04000500_06000700_08000900_0a000b00_0c000d00_0e000f00]
6450000: system.cpu: T0 : 0x1031e @_Z13sumOfElementsPKhm+26. 1 : vwaddu_wv_micro v3, v7, v1 : SimdAdd :  D=[10001100_12001300_14001500_16001700_18001900_1a001b00_1c001d00_1e001f00]
6450000: system.cpu: T0 : 0x10322 @_Z13sumOfElementsPKhm+30    : bgeu a3, a1, 34            : IntAlu : 
6463750: system.cpu: T0 : 0x10344 @_Z13sumOfElementsPKhm+64    : vsetvli zero, a3, e16, m2, ta, ma : SimdConfig :  D=0x0000000000000020
6477500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68    : vredsum_vs v2, v2, v4     
6477500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68. 0 : vredsum_vs_micro v2, v2, v4 : SimdReduceAdd :  D=[78000100_02000300_04000500_06000700_08000900_0a000b00_0c000d00_0e000f00]
6482500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68. 1 : vredsum_vs_micro v2, v3, v4 : SimdReduceAdd :  D=[f0010100_02000300_04000500_06000700_08000900_0a000b00_0c000d00_0e000f00]
6487500: system.cpu: T0 : 0x1034c @_Z13sumOfElementsPKhm+72    : vmv_x_s a0, v2             : SimdMisc :  D=0x00000000000001f0
6488750: system.cpu: T0 : 0x10350 @_Z13sumOfElementsPKhm+76    : c_slli a0, 48              : IntAlu :  D=0x01f0000000000000
6490000: system.cpu: T0 : 0x10352 @_Z13sumOfElementsPKhm+78    : c_srli a0, 48              : IntAlu :  D=0x00000000000001f0
6490000: system.cpu: T0 : 0x10354 @_Z13sumOfElementsPKhm+80    : c_jr ra                    : IntAlu : 
```
Trace from gem5 tag: tag: v24.1.0.0
```
6295000: system.cpu: T0 : 0x10304 @_Z13sumOfElementsPKhm    : vsetvli a3, a1, e16, m2, ta, ma : SimdConfig :  D=0x0000000000000020
6353750: system.cpu: T0 : 0x10308 @_Z13sumOfElementsPKhm+4    : vle8_v v1, (a0)           
6353750: system.cpu: T0 : 0x10308 @_Z13sumOfElementsPKhm+4. 0 : vle8_v_micro v1, 0(a0), zero : SimdUnitStrideLoad :  D=[00010203_04050607_08090a0b_0c0d0e0f_10111213_14151617_18191a1b_1c1d1e1f] A=0x1c160
6360000: system.cpu: T0 : 0x1030c @_Z13sumOfElementsPKhm+8    : vmv_v_i v6, v6, 0         
6360000: system.cpu: T0 : 0x1030c @_Z13sumOfElementsPKhm+8. 0 : vmv_v_i_micro v6, v0, 0    : SimdMisc :  D=[00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000]
6361250: system.cpu: T0 : 0x1030c @_Z13sumOfElementsPKhm+8. 1 : vmv_v_i_micro v7, v1, 0    : SimdMisc :  D=[00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000]
6362500: system.cpu: T0 : 0x10310 @_Z13sumOfElementsPKhm+12    : vsetvli zero, a3, e16, m1, ta, ma : SimdConfig :  D=0x0000000000000010
6432500: system.cpu: T0 : 0x10314 @_Z13sumOfElementsPKhm+16    : vmv_v_i v4, v4, 0         
6432500: system.cpu: T0 : 0x10314 @_Z13sumOfElementsPKhm+16. 0 : vmv_v_i_micro v4, v0, 0    : SimdMisc :  D=[00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000]
6433750: system.cpu: T0 : 0x10318 @_Z13sumOfElementsPKhm+20    : vsetvli zero, a3, e8, m1, ta, ma : SimdConfig :  D=0x0000000000000020
6445000: system.cpu: T0 : 0x1031c @_Z13sumOfElementsPKhm+24    : c_add a0, a3               : IntAlu :  D=0x000000000001c180
6448750: system.cpu: T0 : 0x1031e @_Z13sumOfElementsPKhm+26    : vwaddu_wv v2, v6, v1      
6448750: system.cpu: T0 : 0x1031e @_Z13sumOfElementsPKhm+26. 0 : vwaddu_wv_micro v2, v6, v1 : SimdAdd :  D=[00000100_02000300_04000500_06000700_08000900_0a000b00_0c000d00_0e000f00]
6450000: system.cpu: T0 : 0x1031e @_Z13sumOfElementsPKhm+26. 1 : vwaddu_wv_micro v3, v7, v1 : SimdAdd :  D=[10001100_12001300_14001500_16001700_18001900_1a001b00_1c001d00_1e001f00]
6450000: system.cpu: T0 : 0x10322 @_Z13sumOfElementsPKhm+30    : bgeu a3, a1, 34            : IntAlu : 
6463750: system.cpu: T0 : 0x10344 @_Z13sumOfElementsPKhm+64    : vsetvli zero, a3, e16, m2, ta, ma : SimdConfig :  D=0x0000000000000020
6477500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68    : vredsum_vs v2, v2, v4     
6477500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68. 0 : vredsum_vs_micro v2, v2, v4 : SimdReduceAdd :  D=[7800ffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff]
6478750: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68. 1 : vredsum_vs_micro v2, v3, v4 : SimdReduceAdd :  D=[7801ffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff]
6483750: system.cpu: T0 : 0x1034c @_Z13sumOfElementsPKhm+72    : vmv_x_s a0, v2             : SimdMisc :  D=0x0000000000000178
6485000: system.cpu: T0 : 0x10350 @_Z13sumOfElementsPKhm+76    : c_slli a0, 48              : IntAlu :  D=0x0178000000000000
6486250: system.cpu: T0 : 0x10352 @_Z13sumOfElementsPKhm+78    : c_srli a0, 48              : IntAlu :  D=0x0000000000000178
6486250: system.cpu: T0 : 0x10354 @_Z13sumOfElementsPKhm+80    : c_jr ra                    : IntAlu : 
```
Issue is in 
```
6477500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68    : vredsum_vs v2, v2, v4     
6477500: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68. 0 : vredsum_vs_micro v2, v2, v4 : SimdReduceAdd :  D=[7800ffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff]
6478750: system.cpu: T0 : 0x10348 @_Z13sumOfElementsPKhm+68. 1 : vredsum_vs_micro v2, v3, v4 : SimdReduceAdd :  D=[7801ffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff]
```
vredsum_vs_micro v2, v3, v4 is not adding the reduced sum from v3 and v4 to v2 as required.
**Host Operating System**
Ubuntu 22.04

**Host ISA**
RISC-V

**Compiler used**
riscv64-unknown-elf-gcc

**Additional information**
 We are also noticing this behaviour with many other instructions as well.

### PR DESCRIPTION
**Pull request by 5265325**
This PR fixed the bug(#1668) of vector unit-stride segment load, which is caused by incorrect tail/mask handling logic.

Change-Id: I1a2b3c4d5e6f7890abcdef0123456789abcdef

### CODE REVIEW

File: src/arch/riscv/insts/vector.cc [hunk 1]
```diff
@@ -643,32 +643,57 @@ VlSegDeIntrlvMicroInst::VlSegDeIntrlvMicroInst(ExtMachInst extMachInst,
...
+            } else {
+                vreg_t old_vd;
+                xc->getRegOperand(this, oldDstIdx, &old_vd);
+                memcpy(Vd + (elem * sizeOfElement),
+                       old_vd.as<uint8_t>() + (elem * sizeOfElement),
+                       sizeOfElement);
+            }
             index += numSrcs;
             elem++;
         }
```
Comment (saul44203) [inline src/arch/riscv/insts/vector.cc]: This code should work well for masked off elements but I think it fails to cover the tail (correct me if I'm wrong), since `elems_per_vreg = micro_vl`.

There should be multiple ways to solve this but maybe the simplest is to use something akin to the `COPY_OLD_VD` macro, to the destination register, prior to this code.

File: src/arch/riscv/regs/vector.hh [hunk 2]
```diff
@@ -52,7 +52,7 @@ using vreg_t = VecRegContainer;
 
 
 const int NumVecStandardRegs = 32;
-const int NumVecInternalRegs = 8; // Used by vector uop
+const int NumVecInternalRegs = 32; // Used by vector uop
```
Comment (saul44203) [inline src/arch/riscv/regs/vector.hh]: Is this needed?

**Review by saul44203 — CHANGES_REQUESTED** [review]

File: src/arch/riscv/insts/vector.cc (hunk 1 above)
Comment (Seo-sang) [reply src/arch/riscv/insts/vector.cc]: @saul44203 I really appreciate it.

**Comment by erin-le** [comment]
@5265325 Hello, could you address the comments on this PR when you get a chance? Thank you!

**Comment by erin-le** [comment]
@5265325 Hello, just checking in again. Could you give an update on the status of this PR on your end? Thank you!

**Comment by erin-le** [comment]
@5265325 Hello, just another reminder about this PR. The staging branch for gem5 v25.0 is being created next Tuesday, May 27th, so if you would like to try to get this into the next release, please respond to the comments soon. Thank you!

File: src/arch/riscv/regs/vector.hh (hunk 2 above)
Comment (5265325) [reply src/arch/riscv/regs/vector.hh]: For segment instructions with nf=8 and lmul=8, 32 temporary registers are required. Please correct me if I understand wrongly.

Comment (saul44203) [reply src/arch/riscv/regs/vector.hh]: That would violate the `EMUL * NFIELDS <= 8` restriction per spec. Talking about this, we could also throw an illegal instruction in that case and the vd surpassing index 32 as you did in #2022 if you don't mind.

File: src/arch/riscv/insts/vector.cc [hunk 3]
```diff
@@ -643,36 +643,75 @@ VlSegDeIntrlvMicroInst::VlSegDeIntrlvMicroInst(ExtMachInst extMachInst,
...
+    for (; elem < micro_vlmax; elem++) {
+        if (machInst.vtype8.vma) {
+            memset(Vd + (elem * sizeOfElement), -1, sizeOfElement);
+        } else {
+            memcpy(Vd + (elem * sizeOfElement),
+                   old_vd.as<uint8_t>() + (elem * sizeOfElement),
+                   sizeOfElement);
+        }
+    }
+
```
Comment (saul44203) [inline src/arch/riscv/insts/vector.cc]: This is doing undisturbed for the tail regardless of the vta setting if vma is 0/undisturbed (and we are not even doing masking).

This is not incorrect, but if we want to be consistent right now I think most rvv instructions in gem5 do both tail and mask undisturbed either if vta or vma is 0/undisturbed (ignoring vma if we are not masking), else we do agnostic (so if vta and vma are both 1/agnostic (again, ignoring vma if there's no masking)). 

That's why I mentioned you could do something akin to `COPY_OLD_VD`. This would simplify the code, as you first write the whole register with all 1s or the old values, and then you just need to overwrite in the new elements.

Leaving up to you (and others) on how to approach this.

File: src/arch/riscv/insts/vector.cc [hunk 4]
```diff
@@ -644,36 +644,70 @@ VlSegDeIntrlvMicroInst::VlSegDeIntrlvMicroInst(ExtMachInst extMachInst,
...
-                    s + ((index  %  elems_per_vreg) * sizeOfElement),
-                    sizeOfElement);
+            size_t ei = elem + micro_vlmax * microIdx;
+            if (machInst.vm || elem_mask(v0, ei)) {
+                memcpy(Vd + (elem * sizeOfElement),
+                       s + ((index % elems_per_vreg) * sizeOfElement),
+                       sizeOfElement);
+            } else if (machInst.vtype8.vma) {
+                memset(Vd + (elem * sizeOfElement), -1, sizeOfElement);
+            }
```
Comment (saul44203) [inline src/arch/riscv/insts/vector.cc]: I think this is not needed, as it'll be already filled with ones.

File: src/arch/riscv/insts/vector.cc [hunk 5]
```diff
@@ -644,36 +644,70 @@ VlSegDeIntrlvMicroInst::VlSegDeIntrlvMicroInst(ExtMachInst extMachInst,
...
             index += numSrcs;
             elem++;
         }
     }
+
+    if (machInst.vtype8.vta && elem < micro_vlmax) {
+        memset(Vd + (elem * sizeOfElement), -1,
+            (micro_vlmax - elem) * sizeOfElement);
+    }
+
```
Comment (saul44203) [inline src/arch/riscv/insts/vector.cc]: This too.

**Review by saul44203 — CHANGES_REQUESTED** [review]
Some redundant code. Otherwise LGTM.

File: src/arch/riscv/insts/vector.cc (hunk 4 above)
Comment (5265325) [reply src/arch/riscv/insts/vector.cc]: I think this is necessary. Suppose there is a vset instruction that sets ta but does not set ma (vsetivli zero,16,m1,ta). This code needs to set invalid elements to 1s.

File: src/arch/riscv/insts/vector.cc (hunk 5 above)
Comment (5265325) [reply src/arch/riscv/insts/vector.cc]: Suppose there is an instruction that sets ma but does not set ta (vsetivli zero,16,m1,ma). Then this code is necessary.

File: src/arch/riscv/insts/vector.cc (hunk 4 above)
Comment (saul44203) [reply src/arch/riscv/insts/vector.cc]: You already do this here https://github.com/gem5/gem5/blob/d6ed346d96fa509e90ebbb2b313b8604cfde5245/src/arch/riscv/insts/vector.cc#L679-L685

File: src/arch/riscv/insts/vector.cc (hunk 5 above)
Comment (saul44203) [reply src/arch/riscv/insts/vector.cc]: Same as on the other comment. You already apply either undisturbed or agnostic before this.

File: src/arch/riscv/insts/vector.cc (hunk 4 above)
Comment (5265325) [reply src/arch/riscv/insts/vector.cc]: The vsetivli zero,16,m1,ta instruction means that the tail remains agnostic. But masking elements is gnostic. So the first if (if (!machInst.vtype8.vta || (!machInst.vm && !machInst.vtype8.vma))) will be taken. 
It seems that I need to remove lines 683-684. Because lines 698-699 and 706-709 have replaced these logics.
If I have misunderstood, please correct me.

Comment (saul44203) [reply src/arch/riscv/insts/vector.cc]: Yeah, that's correct. If masked off elements are undisturbed we also do undisturbed tail, even if the tail is agnostic. This is permitted per [spec](https://github.com/riscvarchive/riscv-v-spec/blob/master/v-spec.adoc#343-vector-tail-agnostic-and-vector-mask-agnostic-vta-and-vma):

> When a set is marked agnostic, the corresponding set of destination elements in any vector destination operand can either retain the value they previously held, or are overwritten with 1s. Within a single vector instruction, each destination element can be either left undisturbed or overwritten with 1s, in any combination, and the pattern of undisturbed or overwritten with 1s is not required to be deterministic when the instruction is executed with the same inputs.

 and it's the current behavior on gem5 because it was the simplest (previously gem5 always did undisturbed) that could reduce the data dependencies when using agnostic. 

Basically we apply the same policy to both tail and mask (i.e. both undisturbed if one is (retain old values), else agnostic (fill with 1s)). That's why I say it's redundant.

Comment (5265325) [reply src/arch/riscv/insts/vector.cc]: Understood.

**Review by saul44203 — APPROVED** [review]
LGTM

**Review by powerjg — APPROVED** [review]

**Comment by erin-le** [comment]
@BobbyRBruce: This should be cherry-picked onto the staging branch
